version: '2'
services:
    api-front:
        build: ./front
        volumes:
            - ./front:/app
        ports:
            - 80:5000
        working_dir: /app
        command: /usr/bin/python api.py
